jobs:
- job: Test
  strategy:
    matrix:
      Mac_v4:
        ImageType: 'macOS-latest'
        FileSuffix: '@4'
        MajorVersion: '4'
        OS: mac
      Mac_v3:
        ImageType: 'macOS-latest'
        FileSuffix: '@3'
        MajorVersion: '3'
        OS: mac
      Mac_v3_legacy:
        ImageType: 'macOS-latest'
        FileSuffix: '-v3-preview'
        MajorVersion: '3'
        OS: mac
      Mac_v2:
        ImageType: 'macOS-latest'
        FileSuffix: '@2'
        MajorVersion: '2'
        OS: mac
      Mac_v2_legacy:
        ImageType: 'macOS-latest'
        FileSuffix: ''
        MajorVersion: '2'
        OS: mac
      Linux_v4:
        ImageType: '1es-ubuntu-22.04'
        OS: linux
        FileSuffix: '@4'
        MajorVersion: '4'
      Linux_v3:
        ImageType: '1es-ubuntu-22.04'
        OS: linux
        FileSuffix: '@3'
        MajorVersion: '3'
      Linux_v3_legacy:
        ImageType: '1es-ubuntu-22.04'
        OS: linux
        FileSuffix: '-v3-preview'
        MajorVersion: '3'
      Linux_v2:
        ImageType: '1es-ubuntu-22.04'
        OS: linux
        FileSuffix: '@2'
        MajorVersion: '2'
      Linux_v2_legacy:
        ImageType: '1es-ubuntu-22.04'
        OS: linux
        FileSuffix: ''
        MajorVersion: '2'
  pool:
    vmImage: $(ImageType)
    os: $(OS)
    name: 1es-pool-azfunc
  steps:
  - script: echo "##vso[task.prependpath]/home/linuxbrew/.linuxbrew/bin:/opt/homebrew/bin:/usr/local/bin"
    displayName: 'Add brew to path'
    condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))
  - pwsh: ./test.ps1 -MajorVersion "$(MajorVersion)" -FileSuffix "$(FileSuffix)"
    displayName: 'Test brew formula'