schedules:
- cron: "0 1 * * *"
  displayName: Nightly Build
  branches:
    include:
      - master
  always: true

name: $(Build.SourceBranchName)_$(Build.Reason)

pr:
  branches:
    include:
    - master

trigger:
  batch: true
  branches:
    include:
    - master

resources:
  repositories:
  - repository: 1es
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

extends:
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1es
  parameters:
    pool:
      name: 1es-pool-azfunc-public
      image: 1es-windows-2022
      os: windows
      ${{ if eq( variables['Build.Reason'], 'Schedule' ) }}:
        demands:
        - Priority -equals Low
    sdl:
      codeql:
         compiled:
           enabled: true
         runSourceLanguagesInSourceAnalysis: true
    stages:     
      - stage: Test
        jobs:
        - template: /eng/ci/templates/official/jobs/test-mac.yml@self
        - template: /eng/ci/templates/public/jobs/test-linux-public.yml@self

